### ISSUE TITLE
Error transferring, server replied forbidden

### ISSUE THREAD

**Issue by midhunse** [keshavbhatt/colorwall-issue-tracker#6]
Application not working in my system. Error transferring, server replied forbidden
![Screenshot from 2024-10-04 11-59-20](https://github.com/user-attachments/assets/19ebb9be-ea06-4f88-972f-6bf880826564)
Can you help me with a solution or guide me please.
Thank you.

**Comment by keshavbhatt** [comment]
This issue is fixed in version 2.4 

run `snap refresh colorwall`

Thank you for reporting.

**Comment by midhunse** [comment]
Thank you
